pip uninstall audioread              
pip uninstall bokeh                  
pip uninstall enum34                 
pip uninstall future                 
pip uninstall futures                
pip uninstall intervaltree           
pip uninstall joblib               
pip uninstall librosa                
pip uninstall llvmlite               
pip uninstall magenta                
pip uninstall mido                   
pip uninstall mir-eval             
pip uninstall numba                  
pip uninstall pretty-midi            
pip uninstall python-rtmidi          
pip uninstall resampy                
pip uninstall sortedcontainers       
